baseURL = "https://nikhilweee.me"
languageCode = "en-us"
title = "weeeblog"
theme = ["hugo-whiteglass", "hugo-cite"]

# Used under RSS
copyright = "&copy; Nikhil Verma"

# Number of items to show every page
# Number of items to show every page
pagination.pagerSize = 10

# Use lastmod date from git
enableGitInfo = false

# Enable support for emojis
enableEmoji = true

# Google Analytics
googleAnalytics = "G-0JVB0SEFDJ"

# Disable root /categories
ignoreErrors = ["error-disable-taxonomy"]
disableKinds = ["taxonomy"]

# Disable tags
[taxonomies]
category = 'categories'

# Change permalink format
[permalinks]
blog = "blog/:year/:slug/"
categories = "blog/categories/:slug"
about = "/:slug"

# Minify Output
[minify]
minifyOutput = true
[minify.tdewolff.html]
keepComments = true


# Set feed to feed.xml
[outputFormats]
[outputFormats.RSS]
mediaType = "application/rss+xml"
baseName = "feed"


# Citation style
[params]
citationStyle = "custom"
# Used under every post and in RSS
[params.author]
name = "Nikhil Verma"
email = "nikhilweee@gmail.com"
url = "/"

[markup]
[markup.highlight]
noClasses = false
style = "monokailight"
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 1
endLevel = 3
ordered = false

[menus]
# Default
[[menus.main]]
name = "About"
pageRef = "/"
weight = 10
[[menus.main]]
name = "Blog"
pageRef = "/blog/"
weight = 20
# Homepage
[[menus.about]]
name = "Resume"
pageRef = "/resume/"
weight = 10
[[menus.about]]
name = "Blog"
pageRef = "/blog/"
weight = 20
